FROM nginx:1.17.0
LABEL maintainer Peiyu

COPY nginx.conf /etc/nginx/nginx.conf
COPY uwsgi_params /etc/nginx/uwsgi_params
CMD envsubst '\$ROOT_FOLDER, \$STATIC_FOLDER, \$NGINX_ACCESS_LOG, \$NGINX_ERROR_LOG'  < /nginx.conf.template > /etc/nginx/nginx.conf && \
    exec nginx -g "daemon off;"